common: &common
  recept_date: 来訪日
  recept_time: 訪問時間
  recept_company: 来訪者会社名
  recept_name: 来訪者名
  user: dbuser
  password: |-
    ◆日時
    2019/08/21(水) 19:00

    ◆場所
    〒106-6239
    東京都港区六本木3-2-1
    住友不動産六本木グランドタワー 39F
    https://office.sumitomo-rd.co.jp/63/access.html

    南北線｢六本木一丁目駅｣西改札直結
    日比谷線・大江戸線｢六本木駅」5番出口より徒歩5分

    ◆入館ID
    https://barcode.tec-it.com/barcode.ashx?data=13110365176&code=Code128

    ◆ビル入館方法
    ①（1Fまたは4F）セキュリティゲート前の受付機にバーコードをかざしていただく、もしくは入館IDを入力して下さい。
    ②受付機より「入館証」が発券されます。
    （人数分の発券が必要になります）
    ③入館証のQRコードをゲートにかざし入館します。
    ④ゲート右手のシャトルエレベータで29Fへ。
    ⑤29Fからは36-40F停車のエレベーターにて39Fへお越しください。
    ⑥SmartHR受付のiPadより担当者をお呼び出しください。

    ◆SmartHR新オフィスの行き方
    https://shanaiho.smarthr.co.jp/n/n901fe6fc0e28

    ※注意点
    「入館証」はご退館時まで必要です。大切にお持ち下さい。
dialog:

  tilte: 入館受付申請
  submit: 送信
  recept_company_placeholder: 会社名がない場合は「面接」「なし」等
  recept_name_placeholder: 「様」をつけると入館証が「様様」になるよ！
  <<: *common

   #data = open('./config/message.yml', 'r') { |f| YAML.load(f) }