common: &common
  recept_date: 来訪日
  recept_time: 訪問時間
  recept_datetime: 訪問日時
  recept_company: 来訪者会社名
  recept_name: 来訪者名
  recept_id: 入館ID
  icon: ":office:"
dialog:
  tilte: 入館受付申請
  submit: 送信
  recept_company_placeholder: 会社名がない場合は「面接」「なし」等
  recept_name_placeholder: 「様」をつけると入館証が「様様」になるよ！
  <<: *common
intarctive:
  text_notification: "以下の内容で受け付けました。受け付け完了までしばらくお待ちください :pray:"
  <<: *common
notification:
  text_notification: "入館受付が完了しました :tada:"
  text_guide: |- # RECEPT_DATE, RECEPT_ID は置換部分
    ```
    ◆日時
    RECEPT_DATE

    ◆場所
    〒123-4567
    東京都港区○○ 1-2-3

    ◆入館ID
    RECEPT_ID
    （URLクリックでバーコード画像が表示されます）

    ◆ビル入館方法
    ①セキュリティゲート前の受付機にバーコードをかざしていただく、もしくは入館IDを入力して下さい。
    ②受付機より「入館証」が発券されます。
    （人数分の発券が必要になります）
    ③入館証のQRコードをゲートにかざし入館します。

    ※注意点
    「入館証」はご退館時まで必要です。大切にお持ち下さい。
    ```
  <<: *common